variable:
  - name: subscriptionId
    value: '00000000-0000-0000-0000-000000000000'
  - name: resourceGroup
    value: 'rg-bicep-test'
  - name: location
    value: 'southafricanorth'
  - name: serviceConnection
    value: 'sp-demo-test-001'
  - name: ManagedIdentityEnabled
    value: true
  - name: ManagedIdentityName
    value: 'mi-bicep-test'
  - name: StorageAccountName
    value: 'stbiceptest001'
  