parameters:
  vmImage: 'ubuntu-latest'
  buildConfiguration: 'Release'
  artifactName: 'MyAppArtifact'
  timeoutMinutes: 60

variables:
  imageName: 'mydemoapp'
  tag: '$(Build.BuildId)'  # You can also use $(Build.SourceVersion) or a custom timestamp

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    timeoutInMinutes: ${{ parameters.timeoutMinutes }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        containerRegistry: 'MyACRServiceConnection'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: ${{ parameters.artifactName }}